version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: phonebook
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  contactservice:
    build: ./src/ContactService
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=phonebook;Username=postgres;Password=password
      - Kafka__BootstrapServers=kafka:9092
    depends_on:
      - postgres
      - kafka
    ports:
      - "5001:80"

  reportservice:
    build: ./src/ReportService
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=phonebook;Username=postgres;Password=password
      - Kafka__BootstrapServers=kafka:9092
      - ContactService__BaseUrl=http://contactservice
    depends_on:
      - postgres
      - kafka
    ports:
      - "5002:80"

  apigateway:
    build: ./src/ApiGateway
    depends_on:
      - contactservice
      - reportservice
    ports:
      - "5000:80"

volumes:
  postgres_data: